import React, { useState } from 'react';
import { X, Copy, Check, FileJson, ShieldCheck } from 'lucide-react';
import { WorkbenchProduct } from '../../types/workbench';

interface BulkExportModalProps {
  selectedProducts: WorkbenchProduct[];
  isOpen: boolean;
  onClose: () => void;
}

export const BulkExportModal: React.FC<BulkExportModalProps> = ({
  selectedProducts,
  isOpen,
  onClose
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  // Generate representative Schema.org / JSON-LD export payload
  const exportPayload = {
    "@context": "https://schema.org",
    "@type": "ItemList",
    "name": "AeroPulse Athletics - Canonical Product Intelligence Export",
    "description": "Representative schema export of verified product models with epistemic evidence grounding.",
    "numberOfItems": selectedProducts.length,
    "itemListElement": selectedProducts.map((p, index) => ({
      "@type": "Product",
      "position": index + 1,
      "sku": p.sku,
      "gtin13": p.gtin,
      "mpn": p.mpn,
      "name": p.name,
      "brand": {
        "@type": "Brand",
        "name": p.brand
      },
      "category": p.category,
      "aixshopIntelligence": {
        "canonicalIdentityStatus": p.identityStatus,
        "intelligenceCoveragePercentage": p.intelligenceCoverage,
        "dominantEvidenceState": p.dominantEvidenceState,
        "evidenceBreakdown": p.evidenceBreakdown,
        "remediationPriority": p.priority,
        "discoveryReadinessPercentage": p.discoveryReadiness,
        "modeledKnownClaims": p.whatAIXShopKnows,
        "unverifiedGaps": p.whatAIXShopCannotVerify
      }
    }))
  };

  const jsonString = JSON.stringify(exportPayload, null, 2);

  const handleCopy = () => {
    navigator.clipboard.writeText(jsonString);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-stone-900/40 backdrop-blur-sm animate-in fade-in duration-200">
      <div 
        className="w-full max-w-3xl bg-[#FAF8F5] border border-stone-200 rounded-3xl shadow-2xl overflow-hidden text-stone-900 flex flex-col max-h-[85vh]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-5 border-b border-stone-200 bg-white flex items-start justify-between gap-4 shrink-0">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-[10px] font-mono px-2.5 py-0.5 rounded-full bg-orange-50 text-[#F97316] border border-orange-200 font-medium">
                Schema.org / JSON-LD Preview Export
              </span>
              <span className="text-xs text-stone-500 font-mono">
                {selectedProducts.length} Items Selected
              </span>
            </div>
            <h3 className="text-lg font-bold text-stone-900 tracking-tight">
              Export Canonical Intelligence Model
            </h3>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-xl text-stone-400 hover:text-stone-700 hover:bg-stone-100 transition-colors cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Informative Honest Boundary Notice */}
        <div className="px-5 py-3 bg-amber-50/70 border-b border-amber-200 flex items-center gap-2.5 text-xs text-amber-900">
          <ShieldCheck className="w-4 h-4 text-amber-600 shrink-0" />
          <span>
            <strong>Representative Export Boundary: </strong>This payload previews the structured Schema.org JSON-LD generated by AIXSHOP for feed ingestion and AI answer engines. Direct REST/GraphQL pipelines are part of future integration milestones.
          </span>
        </div>

        {/* JSON Code Window */}
        <div className="flex-1 overflow-auto p-5 bg-stone-900 font-mono text-xs text-stone-200 rounded-xl m-4 border border-stone-800">
          <pre className="whitespace-pre overflow-x-auto leading-relaxed selection:bg-orange-500/30">
            {jsonString}
          </pre>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-stone-200 bg-white flex items-center justify-between text-xs shrink-0">
          <span className="text-stone-500 font-mono text-[11px]">
            Format: application/ld+json · Validated against Schema.org Product specifications
          </span>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopy}
              className="px-3.5 py-1.5 rounded-xl bg-[#F97316] hover:bg-[#EA580C] text-white font-bold transition-colors flex items-center gap-1.5 shadow-xs cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied Payload' : 'Copy Schema'}</span>
            </button>
            <button
              type="button"
              onClick={onClose}
              className="px-3.5 py-1.5 rounded-xl bg-stone-100 hover:bg-stone-200 text-stone-700 transition-colors font-semibold cursor-pointer"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
